### ISSUE TITLE
部分接口是否仍在开发中？

### ISSUE THREAD

**Issue by eigeen** [XiaoMiku01/bilibili-grpc-api-go#1]
一些接口似乎还没有service实现，想了解作者当前的开发进度

**Comment by XiaoMiku01** [comment]
这个项目只是将 [SocialSisterYi/bilibili-API-collect ](https://github.com/SocialSisterYi/bilibili-API-collect) 这里的 grpc 接口全部转成go服务了，其他的还没有加
